apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webscraper

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: webscraper-secrets
    envs:
      - webscraper-secrets.env
