export const JOB_REPOSITORY_TOKEN = Symbol('JOB_REPOSITORY_TOKEN');

export const REDIS_CLIENT_TOKEN = Symbol('REDIS_CLIENT_TOKEN');

export const REDIS_PERSISTENCE_OPTIONS_TOKEN = Symbol(
  'REDIS_PERSISTENCE_OPTIONS_TOKEN',
);

export const DEFAULT_REDIS_JOB_KEY_PREFIX = 'jobs:';

export const DEFAULT_REDIS_JOB_TTL_SECONDS = 60 * 60 * 24;