export const JOB_REPOSITORY_TOKEN = Symbol('JOB_REPOSITORY_TOKEN');

export const JOB_SUBMISSION_STORE_TOKEN = Symbol('JOB_SUBMISSION_STORE_TOKEN');

export const OUTBOX_MESSAGE_STORE_TOKEN = Symbol('OUTBOX_MESSAGE_STORE_TOKEN');

export const POSTGRES_PERSISTENCE_OPTIONS_TOKEN = Symbol(
  'POSTGRES_PERSISTENCE_OPTIONS_TOKEN',
);

export const DEFAULT_JOB_RETENTION_SECONDS = 60 * 60 * 24;

export const DEFAULT_OUTBOX_CLAIM_BATCH_SIZE = 50;

export const DEFAULT_OUTBOX_RETRY_DELAY_MS = 5_000;

export const DEFAULT_OUTBOX_CLAIM_TTL_MS = 30_000;