apiVersion: v1
kind: ConfigMap
metadata:
  name: webscraper-config
data:
  NODE_ENV: production
  LOG_LEVEL: info
  POSTGRES_DB: webscraper
  RABBITMQ_JOB_QUEUE_DEDUPLICATION_ENABLED: "true"
  S3_REGION: us-east-1
  S3_ENDPOINT: http://minio:9000
  S3_FORCE_PATH_STYLE: "true"
  S3_DEFAULT_BUCKET: scrape-results
  SCRAPE_RESULT_PRESIGN_TTL_SECONDS: "300"
